name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'
    workflow_dispatch:

# automatically cancel previously started workflows when pushing a new commit to a branch
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    php:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})'
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        env:
            COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.2'
                      dependency-versions: 'lowest'
                      php-extensions: 'ctype, iconv, mysql, gd'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled
                          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/su_community_test?serverVersion=8.0&charset=utf8mb4'

                    - php-version: '8.2'
                      dependency-versions: 'highest'
                      php-extensions: 'ctype, iconv, mysql, imagick'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/su_community_test?serverVersion=8.0&charset=utf8mb4'

                    - php-version: '8.3'
                      dependency-versions: 'highest'
                      php-extensions: 'ctype, iconv, mysql, imagick'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/su_community_test?serverVersion=8.0&charset=utf8mb4'

                    - php-version: '8.4'
                      dependency-versions: 'highest'
                      php-extensions: 'ctype, iconv, mysql, imagick'
                      tools: 'composer'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/su_community_test?serverVersion=8.0&charset=utf8mb4'

                    - php-version: '8.5'
                      dependency-versions: 'highest'
                      php-extensions: 'ctype, iconv, mysql, imagick'
                      tools: 'composer:snapshot'
                      composer-stability: 'dev'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/su_community_test?serverVersion=8.0&charset=utf8mb4'

        services:
            mysql:
                image: 'mysql:8.0'
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - '3306:3306'
                options: >-
                    --health-cmd="mysqladmin ping" --health-interval=10s
                    --health-timeout=5s --health-retries=5
        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ${{ matrix.php-extensions }}
                  tools: ${{ matrix.tools }}
                  ini-values: memory_limit=-1
                  coverage: none

            - name: Remove Lint Tools
              # These tools are not required to run tests, so we are removing them to improve dependency resolving and
              # testing lowest versions.
              run: composer remove "*php-cs-fixer*" "*phpstan*" "*rector*" --dev --no-update

            - name: Set composer stability
              if: ${{ matrix.composer-stability }}
              run: composer config minimum-stability ${{ matrix.composer-stability }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}
                  composer-options: ${{ matrix.composer-options }}

            - name: Output versions and installed dependencies
              run: |
                  echo 'PHP Version:'
                  php --version
                  echo ''
                  echo 'PHP Modules:'
                  php -m
                  echo ''
                  echo 'Composer Info:'
                  composer info

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment
              env: ${{ matrix.env }}

            - name: Execute test cases
              run: time composer test
              env: ${{ matrix.env }}

    php-lint:
        name: 'PHP Lint'
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        env:
            COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: 'ctype, iconv, mysql, imagick'
                  tools: 'composer:v2'
                  ini-values: memory_limit=-1
                  coverage: none

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Output versions and installed dependencies
              run: |
                  echo 'PHP Version:'
                  php --version
                  echo ''
                  echo 'PHP Modules:'
                  php -m
                  echo ''
                  echo 'Composer Info:'
                  composer info

            - name: Lint code
              run: composer lint
